n = input('Digite algo:')
print('O tipo primitivo desse valor é',type(n))
print('Esse valor é um número:',n.isnumeric())
print('Esse valor é alfabetico:',n.isalpha())
print('Esse valor é alfanúmerico:',n.isalnum())
print('Está em letras minúsculas:',n.islower())
